apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-logs-pv
  labels:
    type: app-logs-storage   # <-- add label here
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/app-logs
  storageClassName: manual    # <-- add storageClassName
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-logs-pvc
  namespace: ivolve
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual   # <-- match storageClassName here
  selector:
    matchLabels:
      type: app-logs-storage   # <-- selector must match PV label

