@Library('cloud_ devops_project') _

pipeline {
  agent { label 'agent-vm' }

  environment {
    AWS_REGION = 'us-east-1'
    ECR_REPO = 'nodejs_app'
    ECR_REGISTRY = '289222951012.dkr.ecr.us-east-1.amazonaws.com'
    IMAGE_TAG = "${BUILD_NUMBER}"
    GIT_CREDENTIALS_ID = 'github'
    CLUSTER_NAME = 'my-eks-cluster'
    NAMESPACE = 'ivolve'
    DEPLOYMENT_FILE = 'deployment.yml'
  }

  stages {

    stage('Build Docker Image') {
      steps { BuildDockerImage() }
    }

    stage('Scan Docker Image Using Trivy') {
      steps { ScanDockerImage() }
    }

    stage('Login to AWS ECR') {
      steps { LoginToEcr() }
    }

    stage('Create ECR Repo if Not Exists') {
      steps { CreateEcrRepo() }
    }

    stage('Tag & Push Docker Image to ECR') {
      steps { TagAndPushImage() }
    }

    stage('Cleanup Local Images') {
      steps { CleanupLocalImages() }
    }

    stage('Clone ArgoCD Manifests Repo') {
      steps { CloneArgoRepo() }
    }

    stage('Update Deployment File with New Image') {
      steps { UpdateDeploymentFile() }
    }
  }

  post {
    success { echo 'Deployment successful' }
    failure { echo 'Deployment failed' }
  }
}
