apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: ivolve
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80              # Publicly accessible port
      targetPort: 3000      # Container port inside the pod
  type: LoadBalancer        # 🔁 Change this from ClusterIP to LoadBalancer

