---
- name: Setup Jenkins Master
  hosts: tag_jenkins_master
  become: true
  roles:
    - aws_cli
    - common
    - git
    - docker
    - java
    - jenkins_master
    - node_exporter

- name: Setup Jenkins Slave
  hosts: tag_jenkins_slave
  become: true
  roles:
    - trivy
    - aws_cli
    - common
    - git
    - docker
    - java
    - node_exporter
