# ---
# - name: EC2 Jenkins Provisioning
#   hosts:
#     - tag_jenkins_master
#     - tag_jenkins_slave
#   become: true
#   roles:
#     - common
#     - git
#     - docker
#     - java
#     - jenkins

---
- name: Setup Jenkins Master
  hosts: tag_jenkins_master
  become: true
  roles:
    - aws_cli
    - common
    - git
    - docker
    - java
    - jenkins_master

- name: Setup Jenkins Slave
  hosts: tag_jenkins_slave
  become: true
  roles:
    - aws_cli
    - common
    - git
    - docker
    - java
