apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: ivolve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "app"
          effect: "NoSchedule"

      initContainers:
        - name: init-mysql-setup
          image: 289222951012.dkr.ecr.us-east-1.amazonaws.com/nodejs_app:2
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_HOST 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for MySQL to be ready..."
              until mysqladmin ping -h $DB_HOST --silent; do
                echo "Waiting for MySQL..."
                sleep 2
              done
              echo "Creating database and user..."
              mysql -h $DB_HOST -u root -p${MYSQL_ROOT_PASSWORD} -e "
                CREATE DATABASE IF NOT EXISTS ivolve;
                CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
                GRANT ALL PRIVILEGES ON ivolve.* TO '${DB_USER}'@'%';
                FLUSH PRIVILEGES;";
              echo "Init container completed."

      containers:
        - name: nodejs-container
          image: 289222951012.dkr.ecr.us-east-1.amazonaws.com/nodejs_app:2
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: logs-storage
              mountPath: /usr/src/app/data

      volumes:
        - name: logs-storage
          emptyDir: {}

